<?php
// ==========================================
// DATABASE CONFIGURATION
// Local XAMPP defaults are intentionally safe for a standard development setup.
// Production values can be supplied with PORTFOLIO_DB_* environment variables.
// ==========================================

$host = getenv('PORTFOLIO_DB_HOST') ?: 'localhost';
$dbPort = getenv('PORTFOLIO_DB_PORT') ?: '3306';
$dbName = getenv('PORTFOLIO_DB_NAME') ?: 'portfolio';
$dbUser = getenv('PORTFOLIO_DB_USER') ?: 'root';
$dbPass = getenv('PORTFOLIO_DB_PASS');
$dbPass = $dbPass === false ? '' : $dbPass;

// Admin credentials are stored in the admin_users database table. Do not add a
// plaintext fallback password or environment-based authentication here.

// Optional app-level settings.
$portfolioTitle = 'Pranshu Yadav | Full-Stack Web Developer & WordPress Specialist';
$portfolioEmail = 'pranshu.rama@gmail.com';

function getDbConnection(): PDO
{
    global $host, $dbPort, $dbName, $dbUser, $dbPass;

    $dsn = 'mysql:host=' . $host . ';port=' . $dbPort . ';dbname=' . $dbName . ';charset=utf8mb4';

    try {
        $pdo = new PDO($dsn, $dbUser, $dbPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
        return $pdo;
    } catch (PDOException $e) {
        error_log('Portfolio database connection failed: ' . $e->getMessage());
        throw new RuntimeException('Database connection failed. Please configure the environment values in includes/config.php.');
    }
}

/** Return the project-relative URL for links generated by shared PHP includes. */
function portfolioUrl(string $path = ''): string
{
    $scriptName = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '');
    $projectDirectory = basename(dirname(__DIR__));
    $marker = '/' . $projectDirectory;
    $position = strpos($scriptName, $marker);
    $baseUrl = $position === false ? '' : substr($scriptName, 0, $position + strlen($marker));

    return $baseUrl . ($path === '' ? '' : '/' . ltrim($path, '/'));
}

function startPortfolioSession(): void
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }

    $isHttps = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (($_SERVER['SERVER_PORT'] ?? null) === '443');

    session_set_cookie_params([
        'lifetime' => 0,
        'path' => '/',
        'secure' => $isHttps,
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}

function getCsrfToken(): string
{
    if (empty($_SESSION['portfolio_csrf_token'])) {
        $_SESSION['portfolio_csrf_token'] = bin2hex(random_bytes(32));
    }

    return $_SESSION['portfolio_csrf_token'];
}

function isValidCsrfToken(?string $token): bool
{
    return is_string($token)
        && isset($_SESSION['portfolio_csrf_token'])
        && hash_equals($_SESSION['portfolio_csrf_token'], $token);
}
?>
